STATUS_TIPS_CHANGE_WIFI_TO_4G = 5
STATUS_TIPS_CHANGE_4G_TO_WIFI = 4
STATUS_NETWORK_UNAVAILABLE = 6
STATUS_WAIT_CHOOSE = 7
STATUS_OPERATION_STREAM_URL = 14
STATUS_OPERATION_REFUSE_QUEUE = 10
STATUS_PLAY_INTERNAL = 1
STATUS_SWITCH_RESOLUTION = 20
STATUS_SWITCH_RESOLUTION_ERROR = 21
STATUS_AUTO_SWITCH_RESOLUTION = 25
STATUS_START_PLAY = 2
STATUS_STOP_PLAY = 3

STATUS_START_RECONNECTION = 8
STATUS_CONNECTION_ERROR = 9
STATUS_MEDIAPLAYER_ERROR = 22
STATUS_TIME_OUT = 23
STATUS_TOAST_NO_INPUT = 11
STATUS_TREFRESH_STOKEN_MAX_TIMES = 12
STATUS_OPERATION_INTERVAL_TIME = 13
STATUS_OPERATION_GAME_OVER = 15
STATUS_OPERATION_WAITING = 16
STATUS_OPERATION_READY_PAUSE_SAAS_SERVER = 17
STATUS_OPERATION_PAUSE_SAAS_SERVER = 18
STATUS_OPERATION_PAUSED_SAAS_SERVER = 19
STATUS_OPERATION_FORCED_OFFLINE = 24
STATUS_SPEED_LOWER_BITRATE = 26
STATUS_OPERATION_OPEN_MORE_SAME_GAME = 27
STATUS_GAME_OVER = 28
STATUS_OPERATION_HMCP_ERROR = 29
STATUS_OPERATION_GAME_TIME_COUNT_DOWN = 30
STATUS_OPERATION_GAME_TIME_UPDATE = 31
STATUS_OPERATION_GAME_TIME_HIGHLIGHT = 32
STATUS_RECEIVE_META_INFOS = 33
STATUS_PLAY_FOR_TEST = 34
STATUS_PAUSE_PLAY = 35
STATUS_OPERATION_NO_INPUT_TIME_REMIND = 36
STATUS_SHOW_SETTING_VIEW = 101
STATUS_FIRST_FRAME_ARRIVAL = 102
STATUS_CLOUDPHONE_ERROR = 100
STATUS_GET_CONTRON_ERROR = 40
STATUS_STRAM_TYPE_ERROR = 41
STATUS_OPERATION_STATE_CHANGE_REASON = 42
STATUS_SWITCH_RESOLUTION_LIST = 43
STATUS_IDCINFO = 44


MESSAGE_TYPE_OTHER = 0
MESSAGE_TYPE_PAY = 1
MESSAGE_TYPE_SYSTEM = 2
MESSAGE_TYPE_TRANSFER = 3

WS_MESSAGE_TYPE_GPS = 0
WS_MESSAGE_TYPE_INTENT = 1
WS_MESSAGE_TYPE_CLIPBOARD = 2

